export { default as Hero } from "./Hero/Hero"
export { default as Sponsors } from "./Sponsors/Sponsors"
export { default as Services } from "./Services/Services"
export { default as CaseStudies } from "./CaseStudies/CaseStudies"
export { default as Footer } from "./Footer/Footer"